analyzer:
  errors:
    always_specify_types: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_print
    - unnecessary_this
    - always_specify_types
